### ISSUE TITLE
Testcases failed

### ISSUE THREAD

**Issue by mechelleamily** [rach0012/humanRL_prior_games#3]
Hi, thank you for sharing this interesting project.

I wanted to walk through these games before creating a customized one. But run into environment problems that I have no clues how to solve. I installed all dependencies such as pygame, gym-ple, PyGame-Learning-Environment, pillow, nose. However, when I run"tests/test_ple.py" I got the following output:

E.EEEEEEEE
======================================================================
ERROR: test_catcher (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 39, in test_catcher
    from ple.games.catcher import Catcher
ModuleNotFoundError: No module named 'ple.games.catcher'
-------------------- >> begin captured stdout << ---------------------
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
couldn't import doomish

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_flappybird (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 49, in test_flappybird
    from ple.games.flappybird import FlappyBird
ModuleNotFoundError: No module named 'ple.games.flappybird'

======================================================================
ERROR: test_monsterkong (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 44, in test_monsterkong
    from ple.games.monsterkong import MonsterKong
ModuleNotFoundError: No module named 'ple.games.monsterkong'

======================================================================
ERROR: test_pixelcopter (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 54, in test_pixelcopter
    from ple.games.pixelcopter import Pixelcopter
ModuleNotFoundError: No module named 'ple.games.pixelcopter'

======================================================================
ERROR: test_pong (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 79, in test_pong
    from ple.games.pong import Pong
ModuleNotFoundError: No module named 'ple.games.pong'

======================================================================
ERROR: test_puckworld (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 59, in test_puckworld
    from ple.games.puckworld import PuckWorld
ModuleNotFoundError: No module named 'ple.games.puckworld'

======================================================================
ERROR: test_raycastmaze (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 64, in test_raycastmaze
    from ple.games.raycastmaze import RaycastMaze
ModuleNotFoundError: No module named 'ple.games.raycastmaze'

======================================================================
ERROR: test_snake (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 69, in test_snake
    from ple.games.snake import Snake
ModuleNotFoundError: No module named 'ple.games.snake'

======================================================================
ERROR: test_waterworld (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_ple.py", line 74, in test_waterworld
    from ple.games.waterworld import WaterWorld
ModuleNotFoundError: No module named 'ple.games.waterworld'

----------------------------------------------------------------------
Ran 10 tests in 0.079s

FAILED (errors=9)

**Comment by rachit-dubey** [comment]
Hi, I think this is most probably because the test_ple file calls the games catcher, pong, monsterkong etc., which I have not included in my current repository (so that you only get the games we created). If you want to run codes on those games, then I recommend just installing PLE by itself without the current repo and running codes on the default PLE games. Hope this helps!
