### ISSUE TITLE
Non-visual state processor failed

### ISSUE THREAD

**Issue by mechelleamily** [rach0012/humanRL_prior_games#4]
I tried to run keras_nonvis.py on originalGame and run into this error. The customized game does not have gameState() implementation, I wonder how your experiments dealt with it? Would you mind sharing a working code?

```
Traceback (most recent call last):
  File "keras_nonviscopy.py", line 86, in <module>
    env = PLE(game, fps=60, state_preprocessor=nv_state_preprocessor)
  File "/Users/Desktop/CCM-Project/paper_games/ple/ple.py", line 142, in __init__
    "Asked to return non-visual state on game that does not support it!")
ValueError: Asked to return non-visual state on game that does not support it!
```

**Comment by rachit-dubey** [comment]
Hmm, this is not something I am super familiar with.. are you able to run keras_nonvis.py on the default PLE games?

**Comment by rachit-dubey** [comment]
Perhaps, you will need to do headless usage of PLE games? If that is the case, then set the following in your code before usage:

os.putenv('SDL_VIDEODRIVER', 'fbcon')
os.environ["SDL_VIDEODRIVER"] = "dummy"

**Comment by mechelleamily** [comment]
Yes I can run keras_nonvis.py on the default PLE agents. However, I hope to replicate the results on the game developed in this paper, but it cannot work without getGame(). 

I can implement getGame() on my own, but I won't be sure whether it works correctly.
