### ISSUE TITLE
Github Page Down

### ISSUE THREAD

**Issue by softyoda** [rach0012/humanRL_prior_games#5]
Hi, the only place I found the original video of gameplay without compiling/executing the game is in [Yannic Kilcher](https://www.youtube.com/@YannicKilcher) [video](https://www.youtube.com/watch?v=Nfry2b4RFI4), would it be possible to make the github page available again or replace the link in the readme with [internet archive](https://web.archive.org/web/20230410181400/https://rach0012.github.io/humanRL_website/) one?

**Comment by rachit-dubey** [comment]
Sorry, I updated my github account and so the previous link was broken. Here's the updated webpage: https://rachit-dubey.github.io/humanRL_website/
